# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "vap-common",
    "vap-client-register",
    "vap-skill-register",
    "vap-skill-framework"
]
